version: "3"

services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    depends_on:
      - redis
    
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    networks:
      - poll-tier
    restart: always

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    networks:
      - poll-tier
      - back-tier

    restart: always

  worker:
    build: ./worker
    networks:
      - back-tier
    depends_on:
      - redis
      - db

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    restart: always

  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    
    networks:
      - result-tier
      - back-tier

    restart: always

  result:
    build: ./result
    ports:
      - "5001:80"
    depends_on:
      - db
    
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    networks:
      - result-tier

    restart: always

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: